{% set version = "1.35.0" %}

package:
  name: yamllint
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/y/yamllint/yamllint-{{ version }}.tar.gz
  sha256: 9bc99c3e9fe89b4c6ee26e17aa817cf2d14390de6577cb6e2e6ed5f72120c835

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation .
  entry_points:
    - yamllint = yamllint.cli:run

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=61
  run:
    - pathspec >=0.5.3
    - python >=3.8
    - pyyaml

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - pytest-cov
  imports:
    - yamllint
  commands:
    - pip check
    - yamllint --help
    - yamllint --version
    - pytest -vv --color=yes --cov=yamllint --cov-branch --cov-report=term-missing:skip-covered --cov-fail-under=98

about:
  home: https://github.com/adrienverge/yamllint
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: A linter for YAML files.
  doc_url: https://yamllint.readthedocs.io
  doc_source_url: |
    https://github.com/adrienverge/yamllint/blob/master/docs/index.rst
  description: |
    yamllint does not only check for syntax validity, but for weirdnesses like
    key repetition and cosmetic problems such as lines length, trailing spaces,
    indentation, etc.

extra:
  recipe-maintainers:
    - proinsias
    - bollwyvl
