# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "1.36.2"

package:
  name: yamllint
  version: ${{ version }}

source:
  - target_directory: dist
    url: https://pypi.org/packages/source/y/yamllint/yamllint-${{ version }}.tar.gz
    sha256: c9ccc818659736e7b13f7e2f9c3c9bb9ac77445be13e789e7d843e92cb8428ef
  - target_directory: src
    url: https://github.com/adrienverge/yamllint/archive/refs/tags/v${{ version }}.tar.gz
    sha256: f5b5dd5f057d47fd206b8bf0bd0a479a93a06ca28cb495af6f85d0f93908903f

build:
  number: 0
  noarch: python
  script:
    - cd dist
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  python:
    entry_points:
      - yamllint = yamllint.cli:run

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools >=61
  run:
    - pathspec >=0.5.3
    - python >=${{ python_min }}
    - pyyaml

tests:
  - python:
      pip_check: true
      python_version: ${{ python_min }}.*
      imports: yamllint
  - files:
      source:
        - src/tests/
    requirements:
      run:
        - pytest
        - pytest-cov
        - python ${{ python_min }}
        - if: win
          then: m2-grep
    script:
      - yamllint --help
      - yamllint --version
      - yamllint --version | grep -iE "${{ version | replace('.', '\\.') }}"
      - cd src
      - coverage run --source=yamllint --branch -m pytest -vv --color=yes --tb=long
      - coverage report --show-missing --skip-covered --fail-under=98

about:
  license: GPL-3.0-or-later
  license_file: dist/LICENSE
  summary: A linter for YAML files.
  homepage: https://github.com/adrienverge/yamllint
  documentation: https://yamllint.readthedocs.io
  description: |
    yamllint does not only check for syntax validity, but for weirdnesses like
    key repetition and cosmetic problems such as lines length, trailing spaces,
    indentation, etc.

extra:
  recipe-maintainers:
    - proinsias
    - bollwyvl
