# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "1.37.1"

package:
  name: yamllint
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/y/yamllint/yamllint-${{ version }}.tar.gz
  sha256: 81f7c0c5559becc8049470d86046b36e96113637bcbe4753ecef06977c00245d

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  python:
    entry_points:
      - yamllint = yamllint.cli:run

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools >=61
  run:
    - pathspec >=0.5.3
    - python >=${{ python_min }}
    - pyyaml

tests:
  - python:
      imports: yamllint
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.13.*
  - files:
      source:
        - tests/
    requirements:
      run:
        - pytest
        - pytest-cov
        - python ${{ python_min }}
        - if: win
          then:
            - m2-grep
    script:
      - yamllint --help
      - yamllint --version
      - yamllint --version | grep -iE "${{ version | replace('.', '\\.') }}"
      - coverage run --source=yamllint --branch -m pytest -vv --color=yes --tb=long -k "not codec_built_in_equivalent"
      - coverage report --show-missing --skip-covered --fail-under=98

about:
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: A linter for YAML files.
  homepage: https://github.com/adrienverge/yamllint
  documentation: https://yamllint.readthedocs.io
  description: |
    yamllint does not only check for syntax validity, but for weirdnesses like
    key repetition and cosmetic problems such as lines length, trailing spaces,
    indentation, etc.

extra:
  recipe-maintainers:
    - proinsias
    - bollwyvl
