# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "1.38.0"
  python_check_max: "3.14"

package:
  name: yamllint
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/y/yamllint/yamllint-${{ version }}.tar.gz
  sha256: 09e5f29531daab93366bb061e76019d5e91691ef0a40328f04c927387d1d364d

build:
  number: 1
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  python:
    entry_points:
      - yamllint = yamllint.cli:run

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools >=77.0.3
  run:
    - pathspec >=1.0.0
    - python >=${{ python_min }}
    - pyyaml

tests:
  - python:
      imports: yamllint
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*
  - files:
      source:
        - tests/
    requirements:
      run:
        - pytest
        - pytest-cov
        - python ${{ python_min }}.*
    script:
      - yamllint --help
      - yamllint --version
      - yamllint --version | python -c "import sys; assert '${{ version }}' in sys.stdin.read().strip();"
      - coverage run --source=yamllint --branch -m pytest -vv --color=yes --tb=long -k "not codec_built_in_equivalent"
      - coverage report --show-missing --skip-covered --fail-under=98

about:
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: A linter for YAML files.
  homepage: https://github.com/adrienverge/yamllint
  documentation: https://yamllint.readthedocs.io
  description: |
    yamllint does not only check for syntax validity, but for weirdnesses like
    key repetition and cosmetic problems such as lines length, trailing spaces,
    indentation, etc.

extra:
  recipe-maintainers:
    - proinsias
    - bollwyvl
