travis:
  secure:
    BINSTAR_TOKEN: VkknhUIWPdIqIg7eaSGgviOR4e+7k0rKinXSDq6pwwirjAF92MEJ3OFa4iIUAkBHAl200LWVlPFWIebgABkCEq1VWirKrtzoGBMrzyWiOdQUZL11XQFhdV3RBcHhVPTaR3rrve50QUoQtq3jeXxWBWnwWnCHjuO/e3Tc9lXNcU6fJH8k/uTP6SAuG3v71pGzTQwlJn8J2Mhte8oTlJSpXgdtT7eiJuWo8NdOWG0GYAoW4DiVvJG9eEOvNwRljDwu1hU2KdapqB28Lt3lZGywoa808f/SHQKgGYHJZFEL5H1EoVeZ8RBIoS6OfopyrruvDu7uDd1V2+V/qlH9F9FOE+Qf0bA9cya7/6raB7wICHEpC6mu73jbftN0OdsSmM4Sbxa1FAAT4q21BnvVK/74sReJl2ouXDequ2BkZQ5A6d5h/5jMF0NlcSc92ceUGHo+szuGakR0BzTreIQydOkbTt7CSoSZS5f4J4uJwQKeo4grQg9cWooXqP/kqtMiMrTaVqrgrhXf0ZsToKUgunULYpcV9/ejjoYUMaoacHw5wMgy2f9GAmujHl+eI5QEWLlpENDCPYF13FzUro1Zsgg+5iYUVj7cJqFREOcDYwI8wtvyLRKvUTQJUMcaOOxAAtzsXfZqDAGrnYSkxn/WeCQnkF3BgMU26+/H/VPxxsF+qr8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
